pipeline {
    agent any
    options{
        buildDiscarder(logRotator(numToKeepStr: '3', daysToKeepStr: '5'))
        timestamps()
        skipStagesAfterUnstable()
    }
    stages {
        stage('1 - Clean workspace') {
            steps {
                sh 'rm -rf monitoring'
            }
        }
        stage('2 - Deploy Aplicação no ArgoCD') {
            steps {
                script {
                    sh ' kubectl apply -f https://raw.githubusercontent.com/RubenSemiao/jenkins-jobs/jobs/monitoring/application.yml'
                }
            }
        }
    }
}