pipeline {
    agent any
    stages {
        stage('Clean workspace') {
            steps {
                sh 'rm -rf openapps'
            }
        }
        stage('Git') {
            steps {
                sh 'git credentialsId: 'github', url: 'https://github.com/RubenSemiao/openapps.git''
            }
        }
        stage('Docker Build') {
            steps {
                sh 'docker build -t rubenalmeida/jenkins:jnlp-1.1.3 . '
            }
        }
    }
}