pipeline {
    agent any
    options{
            buildDiscarder(logRotator(numToKeepStr: '5', daysToKeepStr: '5'))
            timestamps()
        }
        environment{

            registry = "rubenalmeida/website"
            registryCredential = 'docker'
        }
    stages {
        stage('1 - Clean workspace') {
            steps {
                sh 'rm -rf openapps'
            }
        }
        stage('2 - Git') {
            steps {
                git credentialsId: 'github', url: 'https://github.com/RubenSemiao/openapps.git'
            }
        }
        stage('3 - Docker Build') {
            steps {
                sh 'docker build -t rubenalmeida/website:1.6 . '
            }
        }
        stage('4 - Docker Push') {
            steps{
                script {
                  docker.withRegistry( '', registryCredential ) {
                  dockerImage.push()
                  }
                }
            }
        }
        stage('Docker Push') {
            steps {
                sh 'docker push rubenalmeida/website:1.6'
            }
        }
    }
}