name: Trigger Action and Jenkins Job on Directory Changes
on:
  push:
    branches:
      - jobs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3.2.0

      - name: Check for changes
        id: check_changes
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }}..${{ github.sha }} | grep '.*/' || true)
          echo "CHANGES=$changed_files" >> $GITHUB_ENV

      - name: Trigger Jenkins Job
        env:
          CHANGES: ${{ steps.check_changes.outputs.CHANGES }}
        if: env.CHANGES == 'true'
        uses: appleboy/jenkins-action@master
        with:
          url: "https://jenkins.wingdeveloper.pt"
          user: "ruben"
          token: "1197fb5e77c70cd21d6bf18a9497cf79a1"
          job: "Jobs"