name: Trigger Action on Directory Changes
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check for changes
        id: check_changes
        run: |
          changed_files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep '^jobs_dsl/')
          if [[ -n "$changed_files" ]]; then
            echo "Changes detected in the specified directory"
            echo "::set-output name=changes::true"
          else
            echo "No changes in the specified directory"
            echo "::set-output name=changes::false"
          fi

      - name: Trigger action if changes
        if: steps.check_changes.outputs.changes == 'true'
        uses: appleboy/jenkins-action@master
        with:
          url: "https://jenkins.wingdeveloper.pt"
          user: "ruben"
          token: "1197fb5e77c70cd21d6bf18a9497cf79a1"
          job: "Jobs"