name: Trigger Action and Jenkins Job on Directory Changes
on:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Trigger Jenkins Job
        if: steps.check_changes.outputs.changes == 'true'
        uses: appleboy/jenkins-action@master
        with:
          url: "https://jenkins.wingdeveloper.pt"
          user: "ruben"
          token: "1197fb5e77c70cd21d6bf18a9497cf79a1"
          job: "Openapps"
