name: Trigger Jenkins Job
on:
  push:
    branches:
      - main # Replace with the branch name you want to monitor
    paths:
      - 'jobs_dsl' # Replace with the specific directory path

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check conditions
        id: check_conditions
        run: |
          if [[ ${{ github.ref }} == 'refs/heads/main' && -n "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} | grep -E 'jobs_dsl/(openapps.groovy|afiliados.groovy)')" ]]; then
            echo "Triggering Jenkins job"
            echo "Directory changes detected"
          else
            echo "No action needed"
            exit 1
          fi

      - name: Trigger Jenkins Job
        if: steps.check_conditions.outputs.return-code == '0'
        uses: appleboy/jenkins-action@master
        with:
          url: "https://jenkins.wingdeveloper.pt"
          user: "ruben"
          token: "1197fb5e77c70cd21d6bf18a9497cf79a1"
          job: "Jobs"