name: Trigger Jenkins Job
on:
  push:
    branches:
      - openapps # Replace with the branch name you want to monitor


jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Check branch and directory changes
        id: check_changes
        run: |
          if [[ "${{ github.event.repository.name }}" == "https://github.com/RubenSemiao/websites.git" && "${{ github.ref }}" == "refs/heads/dev" && -n "$(git diff --name-only ${{ github.event.before }} ${{ github.sha }})" ]]; then
            echo "Changes detected in the specified branch and directory of the desired repository"
          else
            echo "No changes in the specified branch and directory of the desired repository"
            exit 1
          fi

      - name: Trigger Jenkins Job
        if: steps.check_changes.outputs.return-code == '0'
        uses: appleboy/jenkins-action@master
        with:
          url: "https://jenkins.wingdeveloper.pt"
          user: "ruben"
          token: "1197fb5e77c70cd21d6bf18a9497cf79a1"
          job: "Openapps"